bno08x_driver:
  ros__parameters:

    frame_id: "bno085"

    # Communication Interface
    # Select the communication interface to use 
    # (only one interface can be enabled at a time)
    # This requires a hardware change to the board
    # (see documentation for more information on how to change the interface)
    i2c:
      enabled: false
      bus: "/dev/i2c-18"
      address: "0x4A"

    uart:
      enabled: true
      device: "/dev/ttyUSB0"  

    publish:
      magnetic_field: 
        enabled: true
        rate: 100   # max 100 Hz
      imu:
        enabled: true
        rate: 100   # max 400 Hz 
                    # (anythihng above 100Hz depends on your hardware)
