FKTestNode:
  ros__parameters:
    input_in_degrees: true
    step_loop: false

    command_period: 4.0
    command_topic: "/static_joints_controller/commands"

    joint_sequence_flat:
      - 0.0
      - 0.35
      - 1.92



     