IKTestNode:
  ros__parameters:

    # Foot trajectory (frame: +X backward, +Y outward, +Z down)
    freq: 0.5            # Hz
    amp_z: 0.03          # vertical swing (m)

    x_fixed: 0.05        # (+dir) backward offset (m)
    y_fixed: 0.1        # (+dir) outward offset (m) for right leg
    z_nominal: -0.15     # (+dir) nominal up distance (m)

    dt: 1.0             # update rate (s)
    verbose: true

    # ---- YOUR LINK LENGTHS (set these!) ----
    L2: 0.083            # hip offset (m)
    L3: 0.146            # thigh (m)
    L4: 0.165            # shank (m)
