controller_manager:
  ros__parameters:
    update_rate: 250  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    imu_sensor_controller:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
      publish_rate: 100
      sensor_name: "imu_sensor"

    state_estimator:
      type: quadruped_mpc/state_estimator

    gait_pattern_generator:
      type: quadruped_mpc/gait_pattern_generator

    balance_controller:
      type: quadruped_mpc/balance_controller

    foot_controller:
      type: quadruped_mpc/foot_controller


# Individual controller configurations
joint_state_broadcaster:
  ros__parameters: {}  # Empty is fine, it will auto-discover joints

imu_sensor_controller:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link

state_estimator:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee  
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee
    state_interfaces:
      - position
      - velocity
      - effort

gait_pattern_generator:
  ros__parameters:
    # Gait type is determining the order of steps. The legs are numbered clockwise from the top left like this:
    # |1 2|
    # |4 3|
    gait_type: [2,1,1,2] # [1,3,2,4] #  # Walk
    stance_duration: 0.4
    swing_duration: 0.1
    step_height: 0.1
    # Duplicate MPC parameters here to avoid dependency on balance_controller
    stages: 50    # Number of stages in the MPC
    horizon: 3.0  # Time horizon in seconds

balance_controller:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee  
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee
    # Tuning parameters for the MPC
    mass: 13.2    # Robot mass in kg 
    inertia: 1    # Robot inertia in kg*m^2
    stages: 50    # Number of stages in the MPC
    horizon: 2.0  # Time horizon in seconds
    com_offset: [0.0, 0.02, 0.0]                   # Center of mass offset [x, y, z] in meters
    weights:
      position: [100, 100, 100]                   # Position tracking weights (x, y, z)
      orientation: [100, 100, 100, 100]           # Orientation tracking weights (quaternion)
      velocity: [10, 10, 10]                      # Linear velocity tracking weights
      angular_velocity: [10, 10, 10]              # Angular velocity tracking weights
      force_cost: 1                               # Cost weight for control force inputs
      terminal_factor: 10.0                       # Factor to multiply all weights for terminal cost

foot_controller:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee
    command_interfaces:
      - effort