controller_manager:
  ros__parameters:
    update_rate: 30
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
    zero_joints_controller:
      type: quadruped_utils/ZeroJointsController
    static_joints_controller:
      type: quadruped_utils/StaticJointsController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_group_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - link1_to_base
      - link2_to_link1
      - link3_to_link2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

zero_joints_controller:
  ros__parameters:
    type: quadruped_utils/ZeroJointsController
    zero_effort_lim: 1.0
    kp: 0.0
    kd: 4.0
    velocity: 0.25
    zeroed_kp: 0.0
    zeroed_kd: 0.5
    joints:
      - link1_to_base
      - link2_to_link1
      - link3_to_link2
    zero_direction: [1.0, -1.0, -1.0]
    command_interfaces:
      - position
      - velocity
      - m_state
      - kp
      - kd
      - flip
    state_interfaces:
      - position
      - velocity
      - effort

static_joints_controller:
  ros__parameters:
    type: quadruped_utils/StaticJointsController
    zero_effort_lim: 1.0
    kp: 1.0
    kd: 0.2
    joints:
      - link1_to_base
      - link2_to_link1
      - link3_to_link2
    
    positions: [0.78, 0.78, 0.78]
    velocities: [0.0, 0.0, 0.0]
    command_interfaces:
      - position
      - velocity
      - m_state
      - kp
      - kd
      - flip
    state_interfaces:
      - position
      - velocity
      - effort
